# Generated by Django 6.0.5 on 2026-06-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà trọ')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà trọ',
                'verbose_name_plural': 'Danh sách nhà trọ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('citizen_id', models.CharField(max_length=20, unique=True, verbose_name='Số CCCD')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Người thuê',
                'verbose_name_plural': 'Danh sách người thuê',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng')),
                ('room_name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá thuê hàng tháng')),
                ('area', models.FloatField(verbose_name='Diện tích (m²)')),
                ('status', models.CharField(choices=[('empty', 'Trống'), ('rented', 'Đang thuê')], default='empty', max_length=20, verbose_name='Trạng thái')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='management.house', verbose_name='Thuộc nhà')),
            ],
            options={
                'verbose_name': 'Phòng trọ',
                'verbose_name_plural': 'Danh sách phòng trọ',
                'ordering': ['room_code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tiền cọc')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá thuê')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='management.room', verbose_name='Phòng thuê')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='management.tenant', verbose_name='Người thuê')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Danh sách hợp đồng',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Tháng (YYYY-MM)')),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tiền phòng')),
                ('electricity_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền điện')),
                ('water_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền nước')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Tổng tiền')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Phiếu thu tiền',
                'verbose_name_plural': 'Danh sách phiếu thu',
                'ordering': ['-month', '-created_at'],
                'unique_together': {('room', 'month')},
            },
        ),
    ]
