# Generated by Django 6.0.5 on 2026-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='elec_new',
            field=models.IntegerField(default=0, verbose_name='Chỉ số điện mới'),
        ),
        migrations.AddField(
            model_name='payment',
            name='elec_old',
            field=models.IntegerField(default=0, verbose_name='Chỉ số điện cũ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='elec_price',
            field=models.DecimalField(decimal_places=2, default=3800.0, max_digits=12, verbose_name='Đơn giá điện'),
        ),
        migrations.AddField(
            model_name='payment',
            name='internet_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Tiền Internet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_people',
            field=models.IntegerField(default=1, verbose_name='Số người dịch vụ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Đơn giá dịch vụ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='water_new',
            field=models.IntegerField(default=0, verbose_name='Chỉ số nước mới'),
        ),
        migrations.AddField(
            model_name='payment',
            name='water_old',
            field=models.IntegerField(default=0, verbose_name='Chỉ số nước cũ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='water_price',
            field=models.DecimalField(decimal_places=2, default=35000.0, max_digits=12, verbose_name='Đơn giá nước'),
        ),
    ]
