# Generated by Django 6.0.5 on 2026-06-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_payment_elec_new_payment_elec_old_payment_elec_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Mô tả chi phí')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền chi')),
                ('date', models.DateField(verbose_name='Ngày chi')),
                ('category', models.CharField(choices=[('repair', 'Sửa chữa & Bảo trì'), ('utility', 'Điện nước chung'), ('tax', 'Thuế & Phí'), ('other', 'Chi phí khác')], default='other', max_length=50, verbose_name='Danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='management.house', verbose_name='Thuộc nhà')),
            ],
            options={
                'verbose_name': 'Chi phí',
                'verbose_name_plural': 'Danh sách chi phí',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
