# Generated by Django 6.0.5 on 2026-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bank_account',
            field=models.CharField(blank=True, default='7373700107', max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='house',
            name='bank_name',
            field=models.CharField(blank=True, default='VIETCOMBANK (VCB)', max_length=100, verbose_name='Tên ngân hàng'),
        ),
        migrations.AddField(
            model_name='house',
            name='bank_owner',
            field=models.CharField(blank=True, default='PHẠM VĂN QUANG', max_length=100, verbose_name='Chủ tài khoản'),
        ),
        migrations.AddField(
            model_name='house',
            name='bank_transfer_prefix',
            field=models.CharField(blank=True, default='TS', max_length=20, verbose_name='Mã viết tắt chuyển khoản (VD: TS)'),
        ),
    ]
