# Generated by Django 6.0.5 on 2026-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_house_bank_account_house_bank_name_house_bank_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='occupants_count',
            field=models.IntegerField(default=1, verbose_name='Số người ở'),
        ),
        migrations.AddField(
            model_name='payment',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Phụ phí'),
        ),
        migrations.AddField(
            model_name='payment',
            name='surcharge_desc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lý do phụ phí'),
        ),
    ]
