# Generated by Django 6.0.5 on 2026-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_contract_occupants_count_payment_surcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='elec_price',
            field=models.DecimalField(decimal_places=2, default=3800.0, max_digits=12, verbose_name='Đơn giá điện'),
        ),
        migrations.AddField(
            model_name='house',
            name='internet_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Tiền Internet'),
        ),
        migrations.AddField(
            model_name='house',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Đơn giá dịch vụ'),
        ),
        migrations.AddField(
            model_name='house',
            name='water_price',
            field=models.DecimalField(decimal_places=2, default=35000.0, max_digits=12, verbose_name='Đơn giá nước'),
        ),
    ]
